# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 604ef339cd70d1eb7639f90f76abcb31b932680ba18b1ba3a0c09cd9de3fd58ceefdb6243726151fde21496bd529fdd0b7ab3d7c717d84b20e5aee5d9c8bd38d

test:
  secret_key_base: fda946eb6f41dece1508b11e29f4bb032e98362a1d06d93d195278e61679a81c0fa1c4d88bc81fb6f3dcfc7975cbf32c77263f838d35e21ee771245b07e436c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
